# Generated by Django 2.0.7 on 2018-10-25 08:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181025_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boyb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 10, 25, 16, 11, 29))),
                ('boyb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Boyb')),
            ],
        ),
        migrations.CreateModel(
            name='Girlb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='girlb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Girlb'),
        ),
    ]
