# Generated by Django 2.0.7 on 2018-10-25 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181025_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='boyb',
            name='friends',
            field=models.ManyToManyField(through='user.Friend', to='user.Girlb'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 16, 17, 2, 503906)),
        ),
    ]
